#!/bin/bash

python3 betweennessCentralityRanking.py 
python3 closenessCentralityRanking.py
python3 averageClosenessByCountry.py 
python3 totalPublicationByBetweennessPercentile.py
python3 scatterPlottotalpublicationbybetweennesspercentile.py 
python3 violionChartCountryByPublicationPercentile.py